### ISSUE TITLE
rhel5下g++ 4.1版本编译错误

### ISSUE THREAD

**Issue by geniuslinchao** [mogutt/TTServer#14]
rhel5下默认为g++ 4.1版本编译提示xml错误，修改Makefile中g++为g++44可以编译通过

**Comment by fireco007** [comment]
- -往下翻才发现你也碰到了。

**Comment by bluefoxah** [comment]
应该是jsonxx造成的冲突，新版本中，已经使用了jsoncpp代替jsonxx
