### ISSUE TITLE
redhat 5.9下编译错误

### ISSUE THREAD

**Issue by fireco007** [mogutt/TTServer#20]
gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-54)
编译msfs错误如下：
Compileing common/jsonxx.o...
common/jsonxx.cpp: In member function ‘std::string jsonxx::Object::xml(unsigned int, const std::string&, const std::string&) const’:
common/jsonxx.cpp:792: error: reference to ‘xml’ is ambiguous
include/common/jsonxx.h:74: error: candidates are: std::string jsonxx::xml(std::istream&, unsigned int)
include/common/jsonxx.h:73: error: candidates are: std::string jsonxx::xml(const std::string&, unsigned int)
common/jsonxx.cpp:553: error:                 namespace jsonxx::<unnamed>::xml { }
common/jsonxx.cpp:792: error: ‘xml’ is not a namespace-name
common/jsonxx.cpp:792: error: expected namespace-name before ‘;’ token
common/jsonxx.cpp:799: error: ‘defrootattrib’ was not declared in this scope
common/jsonxx.cpp:799: error: ‘tag’ was not declared in this scope
common/jsonxx.cpp:802: error: ‘defheader’ was not declared in this scope

将jsonxx.cpp中的namespace xml改成了ttxml后ok。应该是和我本地的什么东西冲突了？
可以的话我这边可以提交代码

**Comment by bluefoxah** [comment]
新版本已经去掉了jsonxx，使用jsoncpp代替。
