### ISSUE TITLE
关于LDAP认证

### ISSUE THREAD

**Issue by kenweh** [mogutt/TTServer#23]
ReadMe中好像没有提到使用LDAP做认证的功能，我想多数企业都会尽量避免多套用户/密码，使用LDAP或微软AD来做解决方案的挺多的，至少我们公司这么干了，想找个IM来替换掉RTX~要是有LDAP统一认证支持就好了 :-)

**Comment by bluefoxah** [comment]
感谢您的反馈，我们会考虑的，但是我们不可能把所有的功能都做进去，源码已经开源出去，对于有些需求，可以自己稍作修改，也欢迎给我们贡献代码。
